"""empty message

Revision ID: 1708c7c00643
Revises: 
Create Date: 2020-04-19 14:10:50.335077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1708c7c00643'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'image',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'image',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
