"""empty message

Revision ID: 5bc2d07348dc
Revises: 760cd60323fa
Create Date: 2020-05-05 16:00:59.802591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc2d07348dc'
down_revision = '760cd60323fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('supportimages', sa.Text(), nullable=True))
    op.drop_column('projects', 'supportImages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('supportImages', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('projects', 'supportimages')
    # ### end Alembic commands ###
