"""empty message

Revision ID: 760cd60323fa
Revises: ab672dc528b6
Create Date: 2020-05-05 15:25:48.444930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760cd60323fa'
down_revision = 'ab672dc528b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('supportImages', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'supportImages')
    # ### end Alembic commands ###
