"""empty message

Revision ID: c4fe2c1295cd
Revises: c7b99d2d1b61
Create Date: 2020-04-20 11:39:09.517182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4fe2c1295cd'
down_revision = 'c7b99d2d1b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('moreinfourl', sa.Text(), nullable=True))
    op.drop_column('projects', 'moreInfourl')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('moreInfourl', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('projects', 'moreinfourl')
    # ### end Alembic commands ###
