"""empty message

Revision ID: c7b99d2d1b61
Revises: 82d1810c334d
Create Date: 2020-04-20 11:38:17.987124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b99d2d1b61'
down_revision = '82d1810c334d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('githuburl', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('moreInfourl', sa.Text(), nullable=True))
    op.drop_column('projects', 'githubURL')
    op.drop_column('projects', 'moreInfoURL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('moreInfoURL', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('githubURL', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('projects', 'moreInfourl')
    op.drop_column('projects', 'githuburl')
    # ### end Alembic commands ###
